Fix jq command to use [] instead of ."matrix-js-sdk"
Because otherwise there might be a syntax error looking like
```
error: syntax error, unexpected QQSTRING_START, expecting IDENT
.dependencies."matrix-js-sdk"
```